project:
  type: website

website:
  title: "Law AI Helper Blog"
  site-url: "https://your-username.github.io/law-ai-helper" 
  navbar:
    right:
      - text: "About"
        href: about.qmd
  page-footer:
    left: "© 2025 Shawn"

format:
  html:
    theme: cosmo
    toc: true
